collections:
  sales_test:
    - name: customers
      materialized: true
      origin: "select * from read_json_auto('test/fixtures/customers.jsonl')"
      primary_key:
        - id
    - name: purchases
      origin: "select * from read_csv('test/fixtures/purchases.csv')"
      materialized: true
      before_create:
        - "select 1;"
      after_create:
        - "select 2;"
      primary_key:
        - id
      references:
        - col: customer_id
          ref: customers(id)
