collections:
  sales_test:
    - name: customers
      materialized: true
      origin: "select * from read_csv('test/fixtures/customers.csv')"
      primary_key:
        - id
    - name: purchases
      origin: "select * from read_csv('test/fixtures/purchases.csv')"
      materialized: true
      references:
        - col: customer_id
          ref: customers(id)
          nullable: false        # Required relationship → INNER JOIN
          multiplicity: "1"      # Exactly one customer per purchase  
          join_type: inner       # Explicit JOIN type (inner/left)
